### PR TITLE
Minor html changes

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject. All really minor.

Initially the missing `</head>` was the only thing I added, but then I noticed some other things as well. Only 64030e6 is really 'important', the rest is up to you.

If you agree with all changes, I can squash some of them if desired.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
O and I don't know whether the `charset` declaration is really correct: I haven't tested with non-English systems.

**Comment by unreal** [comment]
Good catch on the missing `</head>` tag. That's what I get for squashing it all into one line quickly.

RE: encoding, I think we should specify utf-8 over iso-8859-1. Do you mind making the change, then I will accept the PR.

Also RE: KUnit itself, are you using it for any projects? I haven't added anything new to this project in a while, but I did use it with some success not too long ago on a pretty complex KAREL program.

**Comment by gavanderhoorn** [comment]
> RE: encoding, I think we should specify utf-8 over iso-8859-1. Do you mind making the change, then I will accept the PR.

Yeah, I figured UTF-8 might make sense, but wasn't too sure about Fanuc actually sticking to it (and not use some weird extended ascii mashup). I'll change it though.

> Also RE: KUnit itself, are you using it for any projects? I haven't added anything new to this project in a while, but I did use it with some success not too long ago on a pretty complex KAREL program.

Yes, I'm currently using it in a project. Have some more stuff I'll PR as well. Thanks for putting it together.

**Comment by gavanderhoorn** [comment]
Just checked and Fanuc claims
```html
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1252">
```
when loading any pages from an English controller.

The server itself does not return any headers. I guess that makes it safe to claim `utf-8` in pages that are under our (KUnit's) control.

**Comment by gavanderhoorn** [comment]
@unreal: updated. Would you like some of this squashed?

**Comment by unreal** [comment]
> @unreal: updated. Would you like some of this squashed?
Great, thanks! I don't mind the extra commits -- merged.

> Yes, I'm currently using it in a project. Have some more stuff I'll PR as well.
Awesome. Looking forward to seeing it. I'm actually beginning a possibly intense KAREL project using the standard Forms/Dictionaries. I'm sure I'll find some things to add too.

**Pull request merged**
